CREATE TABLE EMP_RECORDS (
    EMP_ID        VARCHAR(10) PRIMARY KEY,
    FIRST_NAME    VARCHAR(50),
    LAST_NAME     VARCHAR(50),
    GENDER        CHAR(1),
    ROLE          VARCHAR(100),
    DEPT          VARCHAR(50),
    EXP           INT,
    COUNTRY       VARCHAR(50),
    CONTINENT     VARCHAR(50),
    SALARY        INT,
    EMP_RATING    DECIMAL(3,1),
    MANAGER_ID    VARCHAR(10)
);

CREATE TABLE HR_EMP_TABLE (
    EMP_ID        VARCHAR(10) PRIMARY KEY,
    HIRE_DATE     DATE,
    REGION        VARCHAR(50),
    TRAININGS     INT,
    LAST_PROMO    DATE,
    EXIT_STATUS   VARCHAR(20)
);

CREATE TABLE PROJ_ASSIGN (
    EMP_ID        VARCHAR(10),
    PROJECT_ID    VARCHAR(10),
    START_DATE    DATE,
    END_DATE      DATE,
    BILLABLE      VARCHAR(10),
    HOURS         INT,
    PRIMARY KEY (EMP_ID, PROJECT_ID),

    FOREIGN KEY (EMP_ID) REFERENCES EMP_RECORDS(EMP_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJ_RECORDS(PROJECT_ID)
);

CREATE TABLE PROJ_RECORDS (
    PROJECT_ID      VARCHAR(10) PRIMARY KEY,
    PROJECT_NAME    VARCHAR(100),
    CATEGORY        VARCHAR(50),
    START_DATE      DATE,
    CLOSURE_DATE    DATE,
    DEV_QTR         VARCHAR(10),
    STATUS          VARCHAR(20)
);
